baseURL = 'https://example.com'
languageCode = ''
title = 'Magnolia Default' # This can get overwritten by the single language files
defaultContentLanguage = 'en'
# defaultContentLanguageInSubDir = true
enableRobotsTXT = true
theme = "Magnolia"
googleAnalytics = ""

# BLOG
# Uncomment if you want to disable all posts and tags rendering and indexing
#ignoreFiles= ['posts/*']
#disableKinds = ['taxonomy', 'term']

# Developer area

[taxonomies]
tag = "tags"

[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"
      [[module.mounts]]
      source = 'assets'
      target = 'assets'
  # Prints warning if hugo version is too old
  [module.hugoVersion]
    extended = false
    min = '0.129.0'


  
# To render some markdown otherwise unrendered
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true